[Feature 1 prav] New feature added by Praveen Bandla
mikegithubber/pull-requests pull request #236
Opened 2021-11-07 06:25 UTC by PraveenBandla

I have created new folder 'feature-1-prav' with 2 files

2021-12-01 19:04 UTC, cesetas reviewed
what a code edit. congrat..

2021-12-01 19:07 UTC, cesetas approved these changes

2021-12-01 19:07 UTC, cesetas commented on feature-1-prav/new-file.txt
> +This is new file in feature-1-prav branch created by Praveen Bandla
...

2021-12-01 19:07 UTC, cesetas requested changes

2021-12-01 19:07 UTC, cesetas commented on feature-1-prav/another-file.txt
> +Another new file in feature-1-prav branch created by Praveen Bandla
..

2021-12-07 20:12 UTC, mikegithubber approved these changes
Nicely done. Merging

2021-12-07 20:12 UTC, merged