[Feature_2023-11-12] New feature 2023-11-12 was implemented
mikegithubber/pull-requests pull request #355
Opened 2023-11-13 00:50 UTC by LosingSanity

I have created new folder "feature5" with two files

2023-11-14 05:31 UTC, eric9208 requested changes
change it

2023-11-14 05:32 UTC, eric9208 requested changes

2023-11-14 05:32 UTC, eric9208 commented on feature_2023-11-12/another-file.txt
> +Some other dummy text
change this

2023-11-14 05:32 UTC, eric9208 commented on feature_2023-11-12/new-file.txt
> +New file in the feature_2023-11-12 branch
good

2024-03-16 08:41 UTC, bstashchuk approved these changes

2024-03-16 08:41 UTC, merged